export class OrderRequest {
    id!: string;
    order!: string;
    productName!: string;
    resellerName!: string;
    resellerReferral!: string;
    customerName!: string;
    quantity!: string;
    paymentStatus!: string;
    orderStatus!: string;
    totalAmount!: string;
    paymentMethod!: string;
    bankSlip!: string;
    orderCancled!: string;
    refundNotice!: string;
    productPrice!: string;
    resellPrice!: string;
    trackingNumber!:  string;
    courierName!: string;
    images!: string;
    image1!: string;
    image2!: string;
    image3!: string;
    image4!: string;
    orderPlaceDate!: Date;
    bank_slip!: any;
    OrderDate!:any;
    wayBill!: any;
    remark!: string;
    isStorePickupEnable!: boolean;
    name!: string;
    address!: string;
    contact_1!: string;
    contact_2!: string;
    teamCommision!: string;
    directCommision!: string;
}
